define nltk::downloader (
  $resource = $title,
  $root_dir = "/usr/share/nltk_data",
) {

  # All of the data are stored in a subdirectory of this root
  # directory. Depending on the resource we are looking for, we need
  # to define the subdirectory that is used
  $subdir = $resource ? {
    "abc" => "corpora",
    "alpino" => "corpora",
    "basque_grammars" => "grammars",
    "biocreative_ppi" => "corpora",
    "book_grammars" => "grammars",
    "brown" => "corpora",
    "brown_tei" => "corpora",
    "cess_cat" => "corpora",
    "cess_esp" => "corpora",
    "chat80" => "corpora",
    "city_database" => "corpora",
    "cmudict" => "corpora",
    "conll2000" => "corpora",
    "conll2002" => "corpora",
    "dependency_treebank" => "corpora",
    "europarl_raw" => "corpora",
    "floresta" => "corpora",
    "gazetteers" => "corpora",
    "genesis" => "corpora",
    "gutenberg" => "corpora",
    "hmm_treebank_pos_tagger" => "taggers",
    "ieer" => "corpora",
    "inaugural" => "corpora",
    "indian" => "corpora",
    "kimmo" => "corpora",
    "large_grammars" => "grammars",
    "lin_thesaurus" => "corpora",
    "mac_morpho" => "corpora",
    "maxent_ne_chunker" => "chunkers",
    "maxent_treebank_pos_tagger" => "taggers",
    "movie_reviews" => "corpora",
    "names" => "corpora",
    "nps_chat" => "corpora",
    "paradigms" => "corpora",
    "pil" => "corpora",
    "pl196x" => "corpora",
    "ppattach" => "corpora",
    "problem_reports" => "corpora",
    "ptb" => "corpora",
    "punkt" => "tokenizers",
    "qc" => "corpora",
    "reuters" => "corpora",
    "rslp" => "stemmers",
    "rte" => "corpora",
    "sample_grammars" => "grammars",
    "senseval" => "corpora",
    "shakespeare" => "corpora",
    "sinica_treebank" => "corpora",
    "smultron" => "corpora",
    "spanish_grammars" => "grammars",
    "state_union" => "corpora",
    "stopwords" => "corpora",
    "swadesh" => "corpora",
    "switchboard" => "corpora",
    "timit" => "corpora",
    "toolbox" => "corpora",
    "treebank" => "corpora",
    "udhr2" => "corpora",
    "udhr" => "corpora",
    "unicode_samples" => "corpora",
    "verbnet" => "corpora",
    "webtext" => "corpora",
    "wordnet" => "corpora",
    "wordnet_ic" => "corpora",
    "words" => "corpora",
    "ycoe" => "corpora",
    default => fail("unrecognized corpus name"),
  }
  $dir = "${root_dir}/${subdir}"
    
  exec { "nltk::downloader ${resource}":
    command => "python -m nltk.downloader -d ${root_dir} ${resource}",
    path => ["/usr/bin"],
    creates => "${dir}/${resource}",
    require => Package['nltk'],
  }
}
